---
- name: Listen for events on a webhook
  hosts: all
  # https://ansible.readthedocs.io/projects/rulebook/en/v1.0.2/rulebooks.html
  execution_strategy: parallel 
  sources:
    # https://github.com/ansible/event-driven-ansible/blob/main/extensions/eda/plugins/event_source/webhook.py
    # https://github.com/Dynatrace/Dynatrace-EventDrivenAnsible/blob/main/rulebooks/dt_webhook_event_example_rule.yml
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        token: "{{ token }}"
  rules:
    - name: Display the whole payload
      condition: 1 == 1
      action:
        debug:
          var: event.payload
    - name: Display the whole payload again
      condition: 1 == 1
      action:
        debug:
          var: event.payload
    - name: Run an AAP job
      condition: 2 == 2
      action:
        run_job_template:
          name: "[EDA] reacting to a webhook event"
          organization: Default
          job_args:
            extra_vars:
              payload: "{{ event.payload }}"
