---
- name: Listen for events on a webhook
  hosts: all
  # https://ansible.readthedocs.io/projects/rulebook/en/v1.0.2/rulebooks.html
  # execution_strategy: parallel 
  sources:
    # https://github.com/ansible/event-driven-ansible/blob/main/extensions/eda/plugins/event_source/webhook.py
    # https://github.com/Dynatrace/Dynatrace-EventDrivenAnsible/blob/main/rulebooks/dt_webhook_event_example_rule.yml
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        token: "{{ token }}"
  rules:
    - name: Always run an AAP job and display the payload 
      condition: 1 == 1
      actions:
      - run_job_template:
          name: "[EDA] reacting to a webhook event"
          organization: Default
          job_args:
            extra_vars:
              payload: "{{ event.payload }}"
      - debug:
          var: event.payload
      - print_event:
          pretty: true
